version: "3.9"

services:
  streamlit:
    build: ./Front
    ports:
      - "8501:8501"
    depends_on: 
      - api
    networks:
      - project_network
  api:
    build: ./api
    expose:
      - "8000"
    ports:
      - "8000:8000"
    networks:
      - project_network

networks:
  project_network:
 
